name: Automated test suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: 'poetry'
      - name: Install dependencies
        run: |
          poetry env use '3.10'
          poetry install -E data
      - name: Install Ganache
        run: yarn global add ganache
      - name: Install Anvil
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          PATH=~/.foundry/bin:$PATH
          foundryup
          anvil --version
      - name: Run test scripts
        run: |
          PATH=~/.foundry/bin:$PATH
          poetry run pytest --tb=native
        env:
          BNB_CHAIN_JSON_RPC: ${{ secrets.BNB_CHAIN_JSON_RPC }}
      # Disabled for now
      # https://github.com/reviewdog/action-flake8/issues/40
      # - name: Run flake8
      #  uses: reviewdog/action-flake8@v3
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
  test-compile-abi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize submodules
        run: git submodule update --init --recursive
      - name: Set up NodeJS 14
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
          cache-dependency-path: |
            contracts/sushiswap/yarn.lock
            contracts/uniswap-v3-core/yarn.lock
            contracts/uniswap-v3-periphery/yarn.lock
      - name: Cook sushi
        run: make sushi-and-inhouse
      - name: Copy uniswap v3
        run: make copy-uniswapv3-abi